import type { Metadata } from 'next'
import { Archivo, Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/sections/Header'
import { SiteFooter } from '@/sections/Footer'

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

// Utility/data labels in the masthead — the "dispatch desk" texture.
const jetbrainsMono = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${archivo.variable} ${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className='min-h-dvh'>
        <div className='siaw-grain' aria-hidden />
        <Header />
        {/* <SiteNav /> */}
        {children}
        <SiteFooter />
      </body>
    </html>
  )
}
